name: firebase_storage_mocks
description: Mocks for Firebase Storage. Use this package to write unit tests involving Firebase Storage.
version: 0.6.2
homepage: https://www.wafrat.com
repository: https://github.com/atn832/firebase_storage_mocks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: ^7.0.0
  pedantic: ^1.0.0
  test: ^1.16.5
